name: Reusable Build and Push

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      context:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Push ghcr.io/zhyporium/postgres:${{ inputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add swap for multi-arch builds
        run: |
          sudo swapoff -a || true
          sudo rm -f /swapfile
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - uses: docker/build-push-action@v5
        id: build
        with:
          context: ./${{ inputs.context }}
          file: ./${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/zhyporium/postgres:${{ inputs.tag }}
          labels: |
            org.opencontainers.image.source=https://github.com/zhyporium/postgres

      - run: echo "**Digest:** \`${{ steps.build.outputs.digest }}\`" >> $GITHUB_STEP_SUMMARY
