name: Build postgres-pgvector

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/18/pgvector/**
      - docker/18/common/**
      - .github/workflows/build-postgres-pgvector.yml
      - .github/workflows/_reusable-build.yml

jobs:
  build:
    uses: ./.github/workflows/_reusable-build.yml
    with:
      tag: "18_pgvector"
      context: docker/18
      dockerfile: docker/18/pgvector/Dockerfile
