name: Build postgres-timescale

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker/18/timescale/**
      - docker/18/common/**
      - .github/workflows/build-postgres-timescale.yml
      - .github/workflows/_reusable-build.yml

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_reusable-build.yml
    with:
      tag: "18_timescale"
      context: docker/18
      dockerfile: docker/18/timescale/Dockerfile
